//
// Created by delbek on 7/6/24.
//

#ifndef SUPERMAN_REGISTERS_INC
#define SUPERMAN_REGISTERS_INC


#ifndef REGISTERS
#define REGISTERS                       \
    REG(reg0, 0)                        \
    REG(reg1, 1)                        \
    REG(reg2, 2)                        \
    REG(reg3, 3)                        \
    REG(reg4, 4)                        \
    REG(reg5, 5)                        \
    REG(reg6, 6)                        \
    REG(reg7, 7)                        \
    REG(reg8, 8)                        \
    REG(reg9, 9)                        \
    REG(reg10, 10)                      \
    REG(reg11, 11)                      \
    REG(reg12, 12)                      \
    REG(reg13, 13)                      \
    REG(reg14, 14)                      \
    REG(reg15, 15)                      \
    REG(reg16, 16)                      \
    REG(reg17, 17)                      \
    REG(reg18, 18)                      \
    REG(reg19, 19)                      \
    REG(reg20, 20)                      \
    REG(reg21, 21)                      \
    REG(reg22, 22)                      \
    REG(reg23, 23)                      \
    REG(reg24, 24)                      \
    REG(reg25, 25)                      \
    REG(reg26, 26)                      \
    REG(reg27, 27)                      \
    REG(reg28, 28)                      \
    REG(reg29, 29)                      \
    REG(reg30, 30)                      \
    REG(reg31, 31)                      \
    REG(reg32, 32)                      \
    REG(reg33, 33)                      \
    REG(reg34, 34)                      \
    REG(reg35, 35)                      \
    REG(reg36, 36)                      \
    REG(reg37, 37)                      \
    REG(reg38, 38)                      \
    REG(reg39, 39)
#endif


#endif //SUPERMAN_REGISTERS_INC
