//
// Created by delbek on 7/6/24.
//

#ifndef SUPERMAN_REGISTERS_INC
#define SUPERMAN_REGISTERS_INC


#ifndef REGISTERS
#define REGISTERS     \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)    \
    REG(reg53, 53)    \
    REG(reg54, 54)    \
    REG(reg55, 55)    \
    REG(reg56, 56)    \
    REG(reg57, 57)    \
    REG(reg58, 58)    \
    REG(reg59, 59)    \
    REG(reg60, 60)    \
    REG(reg61, 61)    \
    REG(reg62, 62)
#endif


#ifndef REGISTERS1
#define REGISTERS1   \
    REG(reg0, 0)
#endif


#ifndef REGISTERS2
#define REGISTERS2   \
    REG(reg0, 0)     \
    REG(reg1, 1)
#endif


#ifndef REGISTERS3
#define REGISTERS3   \
    REG(reg0, 0)     \
    REG(reg1, 1)     \
    REG(reg2, 2)
#endif


#ifndef REGISTERS4
#define REGISTERS4   \
    REG(reg0, 0)     \
    REG(reg1, 1)     \
    REG(reg2, 2)     \
    REG(reg3, 3)
#endif


#ifndef REGISTERS5
#define REGISTERS5   \
    REG(reg0, 0)     \
    REG(reg1, 1)     \
    REG(reg2, 2)     \
    REG(reg3, 3)     \
    REG(reg4, 4)
#endif


#ifndef REGISTERS6
#define REGISTERS6   \
    REG(reg0, 0)     \
    REG(reg1, 1)     \
    REG(reg2, 2)     \
    REG(reg3, 3)     \
    REG(reg4, 4)     \
    REG(reg5, 5)
#endif


#ifndef REGISTERS7
#define REGISTERS7   \
    REG(reg0, 0)     \
    REG(reg1, 1)     \
    REG(reg2, 2)     \
    REG(reg3, 3)     \
    REG(reg4, 4)     \
    REG(reg5, 5)     \
    REG(reg6, 6)
#endif


#ifndef REGISTERS8
#define REGISTERS8   \
    REG(reg0, 0)     \
    REG(reg1, 1)     \
    REG(reg2, 2)     \
    REG(reg3, 3)     \
    REG(reg4, 4)     \
    REG(reg5, 5)     \
    REG(reg6, 6)     \
    REG(reg7, 7)
#endif


#ifndef REGISTERS9
#define REGISTERS9   \
    REG(reg0, 0)     \
    REG(reg1, 1)     \
    REG(reg2, 2)     \
    REG(reg3, 3)     \
    REG(reg4, 4)     \
    REG(reg5, 5)     \
    REG(reg6, 6)     \
    REG(reg7, 7)     \
    REG(reg8, 8)
#endif


#ifndef REGISTERS10
#define REGISTERS10   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)
#endif


#ifndef REGISTERS11
#define REGISTERS11   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)
#endif


#ifndef REGISTERS12
#define REGISTERS12   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)
#endif


#ifndef REGISTERS13
#define REGISTERS13   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)
#endif


#ifndef REGISTERS14
#define REGISTERS14   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)
#endif


#ifndef REGISTERS15
#define REGISTERS15   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)
#endif


#ifndef REGISTERS16
#define REGISTERS16   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)
#endif


#ifndef REGISTERS17
#define REGISTERS17   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)
#endif


#ifndef REGISTERS18
#define REGISTERS18   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)
#endif


#ifndef REGISTERS19
#define REGISTERS19   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)
#endif


#ifndef REGISTERS20
#define REGISTERS20   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)
#endif


#ifndef REGISTERS21
#define REGISTERS21   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)
#endif


#ifndef REGISTERS22
#define REGISTERS22   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)
#endif


#ifndef REGISTERS23
#define REGISTERS23   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)
#endif


#ifndef REGISTERS24
#define REGISTERS24   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)
#endif


#ifndef REGISTERS25
#define REGISTERS25   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)
#endif


#ifndef REGISTERS26
#define REGISTERS26   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)
#endif


#ifndef REGISTERS27
#define REGISTERS27   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)
#endif


#ifndef REGISTERS28
#define REGISTERS28   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)
#endif


#ifndef REGISTERS29
#define REGISTERS29   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)
#endif


#ifndef REGISTERS30
#define REGISTERS30   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)
#endif


#ifndef REGISTERS31
#define REGISTERS31   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)
#endif


#ifndef REGISTERS32
#define REGISTERS32   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)
#endif


#ifndef REGISTERS33
#define REGISTERS33   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)
#endif


#ifndef REGISTERS34
#define REGISTERS34   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)
#endif


#ifndef REGISTERS35
#define REGISTERS35   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)
#endif


#ifndef REGISTERS36
#define REGISTERS36   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)
#endif


#ifndef REGISTERS37
#define REGISTERS37   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)
#endif


#ifndef REGISTERS38
#define REGISTERS38   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)
#endif


#ifndef REGISTERS39
#define REGISTERS39   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)
#endif


#ifndef REGISTERS40
#define REGISTERS40   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)
#endif


#ifndef REGISTERS41
#define REGISTERS41   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)
#endif


#ifndef REGISTERS42
#define REGISTERS42   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)
#endif


#ifndef REGISTERS43
#define REGISTERS43   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)
#endif


#ifndef REGISTERS44
#define REGISTERS44   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)
#endif


#ifndef REGISTERS45
#define REGISTERS45   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)
#endif


#ifndef REGISTERS46
#define REGISTERS46   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)
#endif


#ifndef REGISTERS47
#define REGISTERS47   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)
#endif


#ifndef REGISTERS48
#define REGISTERS48   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)
#endif


#ifndef REGISTERS49
#define REGISTERS49   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)
#endif


#ifndef REGISTERS50
#define REGISTERS50   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)
#endif


#ifndef REGISTERS51
#define REGISTERS51   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)
#endif


#ifndef REGISTERS52
#define REGISTERS52   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)
#endif


#ifndef REGISTERS53
#define REGISTERS53   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)
#endif


#ifndef REGISTERS54
#define REGISTERS54   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)    \
    REG(reg53, 53)
#endif


#ifndef REGISTERS55
#define REGISTERS55   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)    \
    REG(reg53, 53)    \
    REG(reg54, 54)
#endif


#ifndef REGISTERS56
#define REGISTERS56   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)    \
    REG(reg53, 53)    \
    REG(reg54, 54)    \
    REG(reg55, 55)
#endif


#ifndef REGISTERS57
#define REGISTERS57   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)    \
    REG(reg53, 53)    \
    REG(reg54, 54)    \
    REG(reg55, 55)    \
    REG(reg56, 56)
#endif


#ifndef REGISTERS58
#define REGISTERS58   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)    \
    REG(reg53, 53)    \
    REG(reg54, 54)    \
    REG(reg55, 55)    \
    REG(reg56, 56)    \
    REG(reg57, 57)
#endif


#ifndef REGISTERS59
#define REGISTERS59   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)    \
    REG(reg53, 53)    \
    REG(reg54, 54)    \
    REG(reg55, 55)    \
    REG(reg56, 56)    \
    REG(reg57, 57)    \
    REG(reg58, 58)
#endif


#ifndef REGISTERS60
#define REGISTERS60   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)    \
    REG(reg53, 53)    \
    REG(reg54, 54)    \
    REG(reg55, 55)    \
    REG(reg56, 56)    \
    REG(reg57, 57)    \
    REG(reg58, 58)    \
    REG(reg59, 59)
#endif


#ifndef REGISTERS61
#define REGISTERS61   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)    \
    REG(reg53, 53)    \
    REG(reg54, 54)    \
    REG(reg55, 55)    \
    REG(reg56, 56)    \
    REG(reg57, 57)    \
    REG(reg58, 58)    \
    REG(reg59, 59)    \
    REG(reg60, 60)
#endif


#ifndef REGISTERS62
#define REGISTERS62   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)    \
    REG(reg53, 53)    \
    REG(reg54, 54)    \
    REG(reg55, 55)    \
    REG(reg56, 56)    \
    REG(reg57, 57)    \
    REG(reg58, 58)    \
    REG(reg59, 59)    \
    REG(reg60, 60)    \
    REG(reg61, 61)
#endif


#ifndef REGISTERS63
#define REGISTERS63   \
    REG(reg0, 0)      \
    REG(reg1, 1)      \
    REG(reg2, 2)      \
    REG(reg3, 3)      \
    REG(reg4, 4)      \
    REG(reg5, 5)      \
    REG(reg6, 6)      \
    REG(reg7, 7)      \
    REG(reg8, 8)      \
    REG(reg9, 9)      \
    REG(reg10, 10)    \
    REG(reg11, 11)    \
    REG(reg12, 12)    \
    REG(reg13, 13)    \
    REG(reg14, 14)    \
    REG(reg15, 15)    \
    REG(reg16, 16)    \
    REG(reg17, 17)    \
    REG(reg18, 18)    \
    REG(reg19, 19)    \
    REG(reg20, 20)    \
    REG(reg21, 21)    \
    REG(reg22, 22)    \
    REG(reg23, 23)    \
    REG(reg24, 24)    \
    REG(reg25, 25)    \
    REG(reg26, 26)    \
    REG(reg27, 27)    \
    REG(reg28, 28)    \
    REG(reg29, 29)    \
    REG(reg30, 30)    \
    REG(reg31, 31)    \
    REG(reg32, 32)    \
    REG(reg33, 33)    \
    REG(reg34, 34)    \
    REG(reg35, 35)    \
    REG(reg36, 36)    \
    REG(reg37, 37)    \
    REG(reg38, 38)    \
    REG(reg39, 39)    \
    REG(reg40, 40)    \
    REG(reg41, 41)    \
    REG(reg42, 42)    \
    REG(reg43, 43)    \
    REG(reg44, 44)    \
    REG(reg45, 45)    \
    REG(reg46, 46)    \
    REG(reg47, 47)    \
    REG(reg48, 48)    \
    REG(reg49, 49)    \
    REG(reg50, 50)    \
    REG(reg51, 51)    \
    REG(reg52, 52)    \
    REG(reg53, 53)    \
    REG(reg54, 54)    \
    REG(reg55, 55)    \
    REG(reg56, 56)    \
    REG(reg57, 57)    \
    REG(reg58, 58)    \
    REG(reg59, 59)    \
    REG(reg60, 60)    \
    REG(reg61, 61)    \
    REG(reg62, 62)
#endif


#endif //SUPERMAN_REGISTERS_INC
